// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A request to create a data transfer configuration. If new credentials are
/// needed for this transfer configuration, authorization info must be provided.
/// If authorization info is provided, the transfer configuration will be
/// associated with the user id corresponding to the authorization info.
/// Otherwise, the transfer configuration will be associated with the calling
/// user.
///
/// When using a cross project service account for creating a transfer config,
/// you must enable cross project service account usage. For more information,
/// see [Disable attachment of service accounts to resources in other
/// projects](https://cloud.google.com/resource-manager/docs/organization-policy/restricting-service-accounts#disable_cross_project_service_accounts).
public struct CreateTransferConfigRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The BigQuery project id where the transfer configuration should
  /// be created. Must be in the format
  /// projects/{project_id}/locations/{location_id} or projects/{project_id}. If
  /// specified location and location of the destination bigquery dataset do not
  /// match - the request will fail.
  public var parent: Swift.String = Swift.String()

  /// Required. Data transfer configuration to create.
  public var transferConfig: TransferConfig? = nil

  /// Deprecated: Authorization code was required when
  /// `transferConfig.dataSourceId` is 'youtube_channel' but it is no longer used
  /// in any data sources. Use `version_info` instead.
  ///
  /// Optional OAuth2 authorization code to use with this transfer configuration.
  /// This is required only if `transferConfig.dataSourceId` is 'youtube_channel'
  /// and new credentials are needed, as indicated by `CheckValidCreds`. In order
  /// to obtain authorization_code, make a request to the following URL:
  /// <pre class="prettyprint" suppresswarning="true">
  /// https://bigquery.cloud.google.com/datatransfer/oauthz/auth?redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=authorization_code&client_id=<var>client_id</var>&scope=<var>data_source_scopes</var>
  /// </pre>
  /// * The <var>client_id</var> is the OAuth client_id of the data source as
  /// returned by ListDataSources method.
  /// * <var>data_source_scopes</var> are the scopes returned by ListDataSources
  /// method.
  ///
  /// Note that this should not be set when `service_account_name` is used to
  /// create the transfer config.
  @available(*, deprecated)
  public var authorizationCode: Swift.String = Swift.String()

  /// Optional version info. This parameter replaces `authorization_code` which
  /// is no longer used in any data sources. This is required only if
  /// `transferConfig.dataSourceId` is 'youtube_channel' *or* new credentials
  /// are needed, as indicated by `CheckValidCreds`. In order to obtain version
  /// info, make a request to the following URL:
  /// <pre class="prettyprint" suppresswarning="true">
  /// https://bigquery.cloud.google.com/datatransfer/oauthz/auth?redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=version_info&client_id=<var>client_id</var>&scope=<var>data_source_scopes</var>
  /// </pre>
  /// * The <var>client_id</var> is the OAuth client_id of the data source as
  /// returned by ListDataSources method.
  /// * <var>data_source_scopes</var> are the scopes returned by ListDataSources
  /// method.
  ///
  /// Note that this should not be set when `service_account_name` is used to
  /// create the transfer config.
  public var versionInfo: Swift.String = Swift.String()

  /// Optional service account email. If this field is set, the transfer config
  /// will be created with this service account's credentials. It requires that
  /// the requesting user calling this API has permissions to act as this service
  /// account.
  ///
  /// Note that not all data sources support service account credentials when
  /// creating a transfer config. For the latest list of data sources, read about
  /// [using service
  /// accounts](https://cloud.google.com/bigquery-transfer/docs/use-service-accounts).
  public var serviceAccountName: Swift.String = Swift.String()

  /// Initialize a new instance of `CreateTransferConfigRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateTransferConfigRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.datatransfer.v1.CreateTransferConfigRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
