// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleCloudGax

/// This API allows users to manage their data transfers into BigQuery.
///
/// @Snippet(path: "DataTransferServiceQuickstart")
public final class DataTransferServiceClient: Clients.DataTransferServiceProtocol, Sendable {
  let inner: any Clients.DataTransferServiceStub

  /// Creates a new `DataTransferServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.DataTransferServiceStub = try Clients.DataTransferServiceTransport(
      options)
    inner = Clients.DataTransferServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.DataTransferServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Retrieves a supported data source and returns its settings.
  ///
  /// @Snippet(path: "DataTransferService_GetDataSource")
  public func getDataSource(
    request: GetDataSourceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.DataSource {
    try await self.inner.getDataSource(request: request, options: options)
  }

  /// Lists supported data sources and returns their settings.
  ///
  /// @Snippet(path: "DataTransferService_ListDataSources")
  public func listDataSources(
    request: ListDataSourcesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.ListDataSourcesResponse {
    try await self.inner.listDataSources(request: request, options: options)
  }

  /// Lists supported data sources and returns their settings.
  ///
  /// @Snippet(path: "DataTransferService_ListDataSources")
  public func listDataSources(
    byItem: ListDataSourcesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<DataSource, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryDataTransferV1.ListDataSourcesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listDataSources(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Creates a new data transfer configuration.
  ///
  /// @Snippet(path: "DataTransferService_CreateTransferConfig")
  public func createTransferConfig(
    request: CreateTransferConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig {
    try await self.inner.createTransferConfig(request: request, options: options)
  }

  /// Updates a data transfer configuration.
  /// All fields must be set, even if they are not updated.
  ///
  /// @Snippet(path: "DataTransferService_UpdateTransferConfig")
  public func updateTransferConfig(
    request: UpdateTransferConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig {
    try await self.inner.updateTransferConfig(request: request, options: options)
  }

  /// Deletes a data transfer configuration, including any associated transfer
  /// runs and logs.
  ///
  /// @Snippet(path: "DataTransferService_DeleteTransferConfig")
  public func deleteTransferConfig(
    request: DeleteTransferConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteTransferConfig(request: request, options: options)
  }

  /// Returns information about a data transfer config.
  ///
  /// @Snippet(path: "DataTransferService_GetTransferConfig")
  public func getTransferConfig(
    request: GetTransferConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig {
    try await self.inner.getTransferConfig(request: request, options: options)
  }

  /// Returns information about all transfer configs owned by a project in the
  /// specified location.
  ///
  /// @Snippet(path: "DataTransferService_ListTransferConfigs")
  public func listTransferConfigs(
    request: ListTransferConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.ListTransferConfigsResponse {
    try await self.inner.listTransferConfigs(request: request, options: options)
  }

  /// Returns information about all transfer configs owned by a project in the
  /// specified location.
  ///
  /// @Snippet(path: "DataTransferService_ListTransferConfigs")
  public func listTransferConfigs(
    byItem: ListTransferConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<TransferConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryDataTransferV1.ListTransferConfigsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listTransferConfigs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Creates transfer runs for a time range [start_time, end_time].
  /// For each date - or whatever granularity the data source supports - in the
  /// range, one transfer run is created.
  /// Note that runs are created per UTC time in the time range.
  /// DEPRECATED: use StartManualTransferRuns instead.
  ///
  /// @Snippet(path: "DataTransferService_ScheduleTransferRuns")
  @available(*, deprecated)
  public func scheduleTransferRuns(
    request: ScheduleTransferRunsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.ScheduleTransferRunsResponse {
    try await self.inner.scheduleTransferRuns(request: request, options: options)
  }

  /// Start manual transfer runs to be executed now with schedule_time equal to
  /// current time. The transfer runs can be created for a time range where the
  /// run_time is between start_time (inclusive) and end_time (exclusive), or for
  /// a specific run_time.
  ///
  /// @Snippet(path: "DataTransferService_StartManualTransferRuns")
  public func startManualTransferRuns(
    request: StartManualTransferRunsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.StartManualTransferRunsResponse {
    try await self.inner.startManualTransferRuns(request: request, options: options)
  }

  /// Returns information about the particular transfer run.
  ///
  /// @Snippet(path: "DataTransferService_GetTransferRun")
  public func getTransferRun(
    request: GetTransferRunRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.TransferRun {
    try await self.inner.getTransferRun(request: request, options: options)
  }

  /// Deletes the specified transfer run.
  ///
  /// @Snippet(path: "DataTransferService_DeleteTransferRun")
  public func deleteTransferRun(
    request: DeleteTransferRunRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteTransferRun(request: request, options: options)
  }

  /// Returns information about running and completed transfer runs.
  ///
  /// @Snippet(path: "DataTransferService_ListTransferRuns")
  public func listTransferRuns(
    request: ListTransferRunsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.ListTransferRunsResponse {
    try await self.inner.listTransferRuns(request: request, options: options)
  }

  /// Returns information about running and completed transfer runs.
  ///
  /// @Snippet(path: "DataTransferService_ListTransferRuns")
  public func listTransferRuns(
    byItem: ListTransferRunsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<TransferRun, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryDataTransferV1.ListTransferRunsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listTransferRuns(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Returns log messages for the transfer run.
  ///
  /// @Snippet(path: "DataTransferService_ListTransferLogs")
  public func listTransferLogs(
    request: ListTransferLogsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.ListTransferLogsResponse {
    try await self.inner.listTransferLogs(request: request, options: options)
  }

  /// Returns log messages for the transfer run.
  ///
  /// @Snippet(path: "DataTransferService_ListTransferLogs")
  public func listTransferLogs(
    byItem: ListTransferLogsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<TransferMessage, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryDataTransferV1.ListTransferLogsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listTransferLogs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Returns true if valid credentials exist for the given data source and
  /// requesting user.
  ///
  /// @Snippet(path: "DataTransferService_CheckValidCreds")
  public func checkValidCreds(
    request: CheckValidCredsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.CheckValidCredsResponse {
    try await self.inner.checkValidCreds(request: request, options: options)
  }

  /// Enroll data sources in a user project. This allows users to create transfer
  /// configurations for these data sources. They will also appear in the
  /// ListDataSources RPC and as such, will appear in the
  /// [BigQuery UI](https://console.cloud.google.com/bigquery), and the documents
  /// can be found in the public guide for
  /// [BigQuery Web UI](https://cloud.google.com/bigquery/bigquery-web-ui) and
  /// [Data Transfer
  /// Service](https://cloud.google.com/bigquery/docs/working-with-transfers).
  ///
  /// @Snippet(path: "DataTransferService_EnrollDataSources")
  public func enrollDataSources(
    request: EnrollDataSourcesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.enrollDataSources(request: request, options: options)
  }

  /// Unenroll data sources in a user project. This allows users to remove
  /// transfer configurations for these data sources. They will no longer appear
  /// in the ListDataSources RPC and will also no longer appear in the [BigQuery
  /// UI](https://console.cloud.google.com/bigquery). Data transfers
  /// configurations of unenrolled data sources will not be scheduled.
  ///
  /// @Snippet(path: "DataTransferService_UnenrollDataSources")
  public func unenrollDataSources(
    request: UnenrollDataSourcesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.unenrollDataSources(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "DataTransferService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "DataTransferService_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "DataTransferService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `DataTransferServiceClient`.
  ///
  /// To mock `DataTransferServiceClient` change your functions to receive
  /// `some DataTransferServiceProtocol` or `any DataTransferServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol DataTransferServiceProtocol {
    /// See `DataTransferServiceClient.getDataSource`.
    func getDataSource(request: GetDataSourceRequest) async throws
      -> GoogleBigQueryDataTransferV1.DataSource

    /// See `DataTransferServiceClient.getDataSource`.
    func getDataSource(
      name: Swift.String,
    ) async throws -> GoogleBigQueryDataTransferV1.DataSource

    /// See `DataTransferServiceClient.listDataSources`.
    func listDataSources(request: ListDataSourcesRequest) async throws
      -> GoogleBigQueryDataTransferV1.ListDataSourcesResponse

    /// See `DataTransferServiceClient.listDataSources`.
    func listDataSources(
      byItem: ListDataSourcesRequest
    ) throws -> any AsyncSequence<DataSource, Swift.Error>

    /// See `DataTransferServiceClient.listDataSources`.
    func listDataSources(
      parent: Swift.String,
    ) throws -> any AsyncSequence<DataSource, Swift.Error>

    /// See `DataTransferServiceClient.createTransferConfig`.
    func createTransferConfig(request: CreateTransferConfigRequest) async throws
      -> GoogleBigQueryDataTransferV1.TransferConfig

    /// See `DataTransferServiceClient.createTransferConfig`.
    func createTransferConfig(
      parent: Swift.String,
      transferConfig: TransferConfig?,
    ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig

    /// See `DataTransferServiceClient.updateTransferConfig`.
    func updateTransferConfig(request: UpdateTransferConfigRequest) async throws
      -> GoogleBigQueryDataTransferV1.TransferConfig

    /// See `DataTransferServiceClient.updateTransferConfig`.
    func updateTransferConfig(
      transferConfig: TransferConfig?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig

    /// See `DataTransferServiceClient.deleteTransferConfig`.
    func deleteTransferConfig(request: DeleteTransferConfigRequest) async throws

    /// See `DataTransferServiceClient.deleteTransferConfig`.
    func deleteTransferConfig(
      name: Swift.String,
    ) async throws

    /// See `DataTransferServiceClient.getTransferConfig`.
    func getTransferConfig(request: GetTransferConfigRequest) async throws
      -> GoogleBigQueryDataTransferV1.TransferConfig

    /// See `DataTransferServiceClient.getTransferConfig`.
    func getTransferConfig(
      name: Swift.String,
    ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig

    /// See `DataTransferServiceClient.listTransferConfigs`.
    func listTransferConfigs(request: ListTransferConfigsRequest) async throws
      -> GoogleBigQueryDataTransferV1.ListTransferConfigsResponse

    /// See `DataTransferServiceClient.listTransferConfigs`.
    func listTransferConfigs(
      byItem: ListTransferConfigsRequest
    ) throws -> any AsyncSequence<TransferConfig, Swift.Error>

    /// See `DataTransferServiceClient.listTransferConfigs`.
    func listTransferConfigs(
      parent: Swift.String,
    ) throws -> any AsyncSequence<TransferConfig, Swift.Error>

    /// See `DataTransferServiceClient.scheduleTransferRuns`.
    @available(*, deprecated)
    func scheduleTransferRuns(request: ScheduleTransferRunsRequest) async throws
      -> GoogleBigQueryDataTransferV1.ScheduleTransferRunsResponse

    /// See `DataTransferServiceClient.scheduleTransferRuns`.
    @available(*, deprecated)
    func scheduleTransferRuns(
      parent: Swift.String,
      startTime: GoogleCloudWKT.Timestamp?,
      endTime: GoogleCloudWKT.Timestamp?,
    ) async throws -> GoogleBigQueryDataTransferV1.ScheduleTransferRunsResponse

    /// See `DataTransferServiceClient.startManualTransferRuns`.
    func startManualTransferRuns(request: StartManualTransferRunsRequest) async throws
      -> GoogleBigQueryDataTransferV1.StartManualTransferRunsResponse

    /// See `DataTransferServiceClient.getTransferRun`.
    func getTransferRun(request: GetTransferRunRequest) async throws
      -> GoogleBigQueryDataTransferV1.TransferRun

    /// See `DataTransferServiceClient.getTransferRun`.
    func getTransferRun(
      name: Swift.String,
    ) async throws -> GoogleBigQueryDataTransferV1.TransferRun

    /// See `DataTransferServiceClient.deleteTransferRun`.
    func deleteTransferRun(request: DeleteTransferRunRequest) async throws

    /// See `DataTransferServiceClient.deleteTransferRun`.
    func deleteTransferRun(
      name: Swift.String,
    ) async throws

    /// See `DataTransferServiceClient.listTransferRuns`.
    func listTransferRuns(request: ListTransferRunsRequest) async throws
      -> GoogleBigQueryDataTransferV1.ListTransferRunsResponse

    /// See `DataTransferServiceClient.listTransferRuns`.
    func listTransferRuns(
      byItem: ListTransferRunsRequest
    ) throws -> any AsyncSequence<TransferRun, Swift.Error>

    /// See `DataTransferServiceClient.listTransferRuns`.
    func listTransferRuns(
      parent: Swift.String,
    ) throws -> any AsyncSequence<TransferRun, Swift.Error>

    /// See `DataTransferServiceClient.listTransferLogs`.
    func listTransferLogs(request: ListTransferLogsRequest) async throws
      -> GoogleBigQueryDataTransferV1.ListTransferLogsResponse

    /// See `DataTransferServiceClient.listTransferLogs`.
    func listTransferLogs(
      byItem: ListTransferLogsRequest
    ) throws -> any AsyncSequence<TransferMessage, Swift.Error>

    /// See `DataTransferServiceClient.listTransferLogs`.
    func listTransferLogs(
      parent: Swift.String,
    ) throws -> any AsyncSequence<TransferMessage, Swift.Error>

    /// See `DataTransferServiceClient.checkValidCreds`.
    func checkValidCreds(request: CheckValidCredsRequest) async throws
      -> GoogleBigQueryDataTransferV1.CheckValidCredsResponse

    /// See `DataTransferServiceClient.checkValidCreds`.
    func checkValidCreds(
      name: Swift.String,
    ) async throws -> GoogleBigQueryDataTransferV1.CheckValidCredsResponse

    /// See `DataTransferServiceClient.enrollDataSources`.
    func enrollDataSources(request: EnrollDataSourcesRequest) async throws

    /// See `DataTransferServiceClient.unenrollDataSources`.
    func unenrollDataSources(request: UnenrollDataSourcesRequest) async throws

    /// See `DataTransferServiceClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `DataTransferServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `DataTransferServiceClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `DataTransferServiceClient.getDataSource`.
    func getDataSource(
      request: GetDataSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.DataSource

    /// See `DataTransferServiceClient.listDataSources`.
    func listDataSources(
      request: ListDataSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ListDataSourcesResponse

    /// See `DataTransferServiceClient.listDataSources`.
    func listDataSources(
      byItem: ListDataSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<DataSource, Swift.Error>

    /// See `DataTransferServiceClient.createTransferConfig`.
    func createTransferConfig(
      request: CreateTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig

    /// See `DataTransferServiceClient.updateTransferConfig`.
    func updateTransferConfig(
      request: UpdateTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig

    /// See `DataTransferServiceClient.deleteTransferConfig`.
    func deleteTransferConfig(
      request: DeleteTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `DataTransferServiceClient.getTransferConfig`.
    func getTransferConfig(
      request: GetTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig

    /// See `DataTransferServiceClient.listTransferConfigs`.
    func listTransferConfigs(
      request: ListTransferConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ListTransferConfigsResponse

    /// See `DataTransferServiceClient.listTransferConfigs`.
    func listTransferConfigs(
      byItem: ListTransferConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<TransferConfig, Swift.Error>

    /// See `DataTransferServiceClient.scheduleTransferRuns`.
    @available(*, deprecated)
    func scheduleTransferRuns(
      request: ScheduleTransferRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ScheduleTransferRunsResponse

    /// See `DataTransferServiceClient.startManualTransferRuns`.
    func startManualTransferRuns(
      request: StartManualTransferRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.StartManualTransferRunsResponse

    /// See `DataTransferServiceClient.getTransferRun`.
    func getTransferRun(
      request: GetTransferRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.TransferRun

    /// See `DataTransferServiceClient.deleteTransferRun`.
    func deleteTransferRun(
      request: DeleteTransferRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `DataTransferServiceClient.listTransferRuns`.
    func listTransferRuns(
      request: ListTransferRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ListTransferRunsResponse

    /// See `DataTransferServiceClient.listTransferRuns`.
    func listTransferRuns(
      byItem: ListTransferRunsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<TransferRun, Swift.Error>

    /// See `DataTransferServiceClient.listTransferLogs`.
    func listTransferLogs(
      request: ListTransferLogsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ListTransferLogsResponse

    /// See `DataTransferServiceClient.listTransferLogs`.
    func listTransferLogs(
      byItem: ListTransferLogsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<TransferMessage, Swift.Error>

    /// See `DataTransferServiceClient.checkValidCreds`.
    func checkValidCreds(
      request: CheckValidCredsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.CheckValidCredsResponse

    /// See `DataTransferServiceClient.enrollDataSources`.
    func enrollDataSources(
      request: EnrollDataSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `DataTransferServiceClient.unenrollDataSources`.
    func unenrollDataSources(
      request: UnenrollDataSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `DataTransferServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `DataTransferServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `DataTransferServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}

// Default implementations
extension Clients.DataTransferServiceProtocol {
  public func getDataSource(request: GetDataSourceRequest) async throws
    -> GoogleBigQueryDataTransferV1.DataSource
  {
    try await self.getDataSource(request: request, options: .init())
  }

  public func getDataSource(
    request: GetDataSourceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.DataSource {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getDataSource(
    name: Swift.String,
  ) async throws -> GoogleBigQueryDataTransferV1.DataSource {
    let request = GetDataSourceRequest().with {
      $0.name = name
    }
    return try await self.getDataSource(request: request)
  }

  public func listDataSources(request: ListDataSourcesRequest) async throws
    -> GoogleBigQueryDataTransferV1.ListDataSourcesResponse
  {
    try await self.listDataSources(request: request, options: .init())
  }

  public func listDataSources(
    request: ListDataSourcesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.ListDataSourcesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listDataSources(
    byItem: ListDataSourcesRequest
  ) throws -> any AsyncSequence<DataSource, Swift.Error> {
    try self.listDataSources(byItem: byItem, options: .init())
  }

  public func listDataSources(
    byItem: ListDataSourcesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<DataSource, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryDataTransferV1.ListDataSourcesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDataSources(
    parent: Swift.String,
  ) throws -> any AsyncSequence<DataSource, Swift.Error> {
    let request = ListDataSourcesRequest().with {
      $0.parent = parent
    }
    return try self.listDataSources(byItem: request)
  }

  public func createTransferConfig(request: CreateTransferConfigRequest) async throws
    -> GoogleBigQueryDataTransferV1.TransferConfig
  {
    try await self.createTransferConfig(request: request, options: .init())
  }

  public func createTransferConfig(
    request: CreateTransferConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createTransferConfig(
    parent: Swift.String,
    transferConfig: TransferConfig?,
  ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig {
    let request = CreateTransferConfigRequest().with {
      $0.parent = parent
      $0.transferConfig = transferConfig
    }
    return try await self.createTransferConfig(request: request)
  }

  public func updateTransferConfig(request: UpdateTransferConfigRequest) async throws
    -> GoogleBigQueryDataTransferV1.TransferConfig
  {
    try await self.updateTransferConfig(request: request, options: .init())
  }

  public func updateTransferConfig(
    request: UpdateTransferConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateTransferConfig(
    transferConfig: TransferConfig?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig {
    let request = UpdateTransferConfigRequest().with {
      $0.transferConfig = transferConfig
      $0.updateMask = updateMask
    }
    return try await self.updateTransferConfig(request: request)
  }

  public func deleteTransferConfig(request: DeleteTransferConfigRequest) async throws {
    try await self.deleteTransferConfig(request: request, options: .init())
  }

  public func deleteTransferConfig(
    request: DeleteTransferConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteTransferConfig(
    name: Swift.String,
  ) async throws {
    let request = DeleteTransferConfigRequest().with {
      $0.name = name
    }
    try await self.deleteTransferConfig(request: request)
  }

  public func getTransferConfig(request: GetTransferConfigRequest) async throws
    -> GoogleBigQueryDataTransferV1.TransferConfig
  {
    try await self.getTransferConfig(request: request, options: .init())
  }

  public func getTransferConfig(
    request: GetTransferConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getTransferConfig(
    name: Swift.String,
  ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig {
    let request = GetTransferConfigRequest().with {
      $0.name = name
    }
    return try await self.getTransferConfig(request: request)
  }

  public func listTransferConfigs(request: ListTransferConfigsRequest) async throws
    -> GoogleBigQueryDataTransferV1.ListTransferConfigsResponse
  {
    try await self.listTransferConfigs(request: request, options: .init())
  }

  public func listTransferConfigs(
    request: ListTransferConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.ListTransferConfigsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listTransferConfigs(
    byItem: ListTransferConfigsRequest
  ) throws -> any AsyncSequence<TransferConfig, Swift.Error> {
    try self.listTransferConfigs(byItem: byItem, options: .init())
  }

  public func listTransferConfigs(
    byItem: ListTransferConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<TransferConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryDataTransferV1.ListTransferConfigsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listTransferConfigs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<TransferConfig, Swift.Error> {
    let request = ListTransferConfigsRequest().with {
      $0.parent = parent
    }
    return try self.listTransferConfigs(byItem: request)
  }

  @available(*, deprecated)
  public func scheduleTransferRuns(request: ScheduleTransferRunsRequest) async throws
    -> GoogleBigQueryDataTransferV1.ScheduleTransferRunsResponse
  {
    try await self.scheduleTransferRuns(request: request, options: .init())
  }

  @available(*, deprecated)
  public func scheduleTransferRuns(
    request: ScheduleTransferRunsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.ScheduleTransferRunsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func scheduleTransferRuns(
    parent: Swift.String,
    startTime: GoogleCloudWKT.Timestamp?,
    endTime: GoogleCloudWKT.Timestamp?,
  ) async throws -> GoogleBigQueryDataTransferV1.ScheduleTransferRunsResponse {
    let request = ScheduleTransferRunsRequest().with {
      $0.parent = parent
      $0.startTime = startTime
      $0.endTime = endTime
    }
    return try await self.scheduleTransferRuns(request: request)
  }

  public func startManualTransferRuns(request: StartManualTransferRunsRequest) async throws
    -> GoogleBigQueryDataTransferV1.StartManualTransferRunsResponse
  {
    try await self.startManualTransferRuns(request: request, options: .init())
  }

  public func startManualTransferRuns(
    request: StartManualTransferRunsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.StartManualTransferRunsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getTransferRun(request: GetTransferRunRequest) async throws
    -> GoogleBigQueryDataTransferV1.TransferRun
  {
    try await self.getTransferRun(request: request, options: .init())
  }

  public func getTransferRun(
    request: GetTransferRunRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.TransferRun {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getTransferRun(
    name: Swift.String,
  ) async throws -> GoogleBigQueryDataTransferV1.TransferRun {
    let request = GetTransferRunRequest().with {
      $0.name = name
    }
    return try await self.getTransferRun(request: request)
  }

  public func deleteTransferRun(request: DeleteTransferRunRequest) async throws {
    try await self.deleteTransferRun(request: request, options: .init())
  }

  public func deleteTransferRun(
    request: DeleteTransferRunRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteTransferRun(
    name: Swift.String,
  ) async throws {
    let request = DeleteTransferRunRequest().with {
      $0.name = name
    }
    try await self.deleteTransferRun(request: request)
  }

  public func listTransferRuns(request: ListTransferRunsRequest) async throws
    -> GoogleBigQueryDataTransferV1.ListTransferRunsResponse
  {
    try await self.listTransferRuns(request: request, options: .init())
  }

  public func listTransferRuns(
    request: ListTransferRunsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.ListTransferRunsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listTransferRuns(
    byItem: ListTransferRunsRequest
  ) throws -> any AsyncSequence<TransferRun, Swift.Error> {
    try self.listTransferRuns(byItem: byItem, options: .init())
  }

  public func listTransferRuns(
    byItem: ListTransferRunsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<TransferRun, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryDataTransferV1.ListTransferRunsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listTransferRuns(
    parent: Swift.String,
  ) throws -> any AsyncSequence<TransferRun, Swift.Error> {
    let request = ListTransferRunsRequest().with {
      $0.parent = parent
    }
    return try self.listTransferRuns(byItem: request)
  }

  public func listTransferLogs(request: ListTransferLogsRequest) async throws
    -> GoogleBigQueryDataTransferV1.ListTransferLogsResponse
  {
    try await self.listTransferLogs(request: request, options: .init())
  }

  public func listTransferLogs(
    request: ListTransferLogsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.ListTransferLogsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listTransferLogs(
    byItem: ListTransferLogsRequest
  ) throws -> any AsyncSequence<TransferMessage, Swift.Error> {
    try self.listTransferLogs(byItem: byItem, options: .init())
  }

  public func listTransferLogs(
    byItem: ListTransferLogsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<TransferMessage, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryDataTransferV1.ListTransferLogsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listTransferLogs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<TransferMessage, Swift.Error> {
    let request = ListTransferLogsRequest().with {
      $0.parent = parent
    }
    return try self.listTransferLogs(byItem: request)
  }

  public func checkValidCreds(request: CheckValidCredsRequest) async throws
    -> GoogleBigQueryDataTransferV1.CheckValidCredsResponse
  {
    try await self.checkValidCreds(request: request, options: .init())
  }

  public func checkValidCreds(
    request: CheckValidCredsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryDataTransferV1.CheckValidCredsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func checkValidCreds(
    name: Swift.String,
  ) async throws -> GoogleBigQueryDataTransferV1.CheckValidCredsResponse {
    let request = CheckValidCredsRequest().with {
      $0.name = name
    }
    return try await self.checkValidCreds(request: request)
  }

  public func enrollDataSources(request: EnrollDataSourcesRequest) async throws {
    try await self.enrollDataSources(request: request, options: .init())
  }

  public func enrollDataSources(
    request: EnrollDataSourcesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func unenrollDataSources(request: UnenrollDataSourcesRequest) async throws {
    try await self.unenrollDataSources(request: request, options: .init())
  }

  public func unenrollDataSources(
    request: UnenrollDataSourcesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
