// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class DataTransferServiceRetry: DataTransferServiceStub {
    let inner: any DataTransferServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any DataTransferServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func getDataSource(
      request: GetDataSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.DataSource {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDataSourceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.DataSource
          in
          return try await self.inner.getDataSource(request: r, options: o)
        })
    }

    public func listDataSources(
      request: ListDataSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ListDataSourcesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDataSourcesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.ListDataSourcesResponse
          in
          return try await self.inner.listDataSources(request: r, options: o)
        })
    }

    public func createTransferConfig(
      request: CreateTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateTransferConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.TransferConfig
          in
          return try await self.inner.createTransferConfig(request: r, options: o)
        })
    }

    public func updateTransferConfig(
      request: UpdateTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateTransferConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.TransferConfig
          in
          return try await self.inner.updateTransferConfig(request: r, options: o)
        })
    }

    public func deleteTransferConfig(
      request: DeleteTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteTransferConfigRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTransferConfig(request: r, options: o)
        })
    }

    public func getTransferConfig(
      request: GetTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetTransferConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.TransferConfig
          in
          return try await self.inner.getTransferConfig(request: r, options: o)
        })
    }

    public func listTransferConfigs(
      request: ListTransferConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ListTransferConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListTransferConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.ListTransferConfigsResponse
          in
          return try await self.inner.listTransferConfigs(request: r, options: o)
        })
    }

    public func scheduleTransferRuns(
      request: ScheduleTransferRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ScheduleTransferRunsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ScheduleTransferRunsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.ScheduleTransferRunsResponse
          in
          return try await self.inner.scheduleTransferRuns(request: r, options: o)
        })
    }

    public func startManualTransferRuns(
      request: StartManualTransferRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.StartManualTransferRunsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: StartManualTransferRunsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.StartManualTransferRunsResponse
          in
          return try await self.inner.startManualTransferRuns(request: r, options: o)
        })
    }

    public func getTransferRun(
      request: GetTransferRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.TransferRun {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetTransferRunRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.TransferRun
          in
          return try await self.inner.getTransferRun(request: r, options: o)
        })
    }

    public func deleteTransferRun(
      request: DeleteTransferRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteTransferRunRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTransferRun(request: r, options: o)
        })
    }

    public func listTransferRuns(
      request: ListTransferRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ListTransferRunsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListTransferRunsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.ListTransferRunsResponse
          in
          return try await self.inner.listTransferRuns(request: r, options: o)
        })
    }

    public func listTransferLogs(
      request: ListTransferLogsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ListTransferLogsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListTransferLogsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.ListTransferLogsResponse
          in
          return try await self.inner.listTransferLogs(request: r, options: o)
        })
    }

    public func checkValidCreds(
      request: CheckValidCredsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.CheckValidCredsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CheckValidCredsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.CheckValidCredsResponse
          in
          return try await self.inner.checkValidCreds(request: r, options: o)
        })
    }

    public func enrollDataSources(
      request: EnrollDataSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: EnrollDataSourcesRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.enrollDataSources(request: r, options: o)
        })
    }

    public func unenrollDataSources(
      request: UnenrollDataSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UnenrollDataSourcesRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.unenrollDataSources(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
