// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class DataTransferServiceLogging: DataTransferServiceStub {
    let inner: any DataTransferServiceStub
    let logger: Logger

    public init(_ inner: any DataTransferServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-bigquery-datatransfer-v1"
      logger[metadataKey: "gcp.client.service"] = "bigquerydatatransfer"
      logger[metadataKey: "gcp.experimental.swift.client"] = "DataTransferService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func getDataSource(
      request: GetDataSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.DataSource {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDataSource",
        action: {
          (r: GetDataSourceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.DataSource
          in
          return try await self.inner.getDataSource(request: r, options: o)
        })
    }

    public func listDataSources(
      request: ListDataSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ListDataSourcesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDataSources",
        action: {
          (r: ListDataSourcesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.ListDataSourcesResponse
          in
          return try await self.inner.listDataSources(request: r, options: o)
        })
    }

    public func createTransferConfig(
      request: CreateTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTransferConfig",
        action: {
          (r: CreateTransferConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.TransferConfig
          in
          return try await self.inner.createTransferConfig(request: r, options: o)
        })
    }

    public func updateTransferConfig(
      request: UpdateTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTransferConfig",
        action: {
          (r: UpdateTransferConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.TransferConfig
          in
          return try await self.inner.updateTransferConfig(request: r, options: o)
        })
    }

    public func deleteTransferConfig(
      request: DeleteTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTransferConfig",
        action: {
          (r: DeleteTransferConfigRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTransferConfig(request: r, options: o)
        })
    }

    public func getTransferConfig(
      request: GetTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTransferConfig",
        action: {
          (r: GetTransferConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.TransferConfig
          in
          return try await self.inner.getTransferConfig(request: r, options: o)
        })
    }

    public func listTransferConfigs(
      request: ListTransferConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ListTransferConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTransferConfigs",
        action: {
          (r: ListTransferConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.ListTransferConfigsResponse
          in
          return try await self.inner.listTransferConfigs(request: r, options: o)
        })
    }

    public func scheduleTransferRuns(
      request: ScheduleTransferRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ScheduleTransferRunsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "scheduleTransferRuns",
        action: {
          (r: ScheduleTransferRunsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.ScheduleTransferRunsResponse
          in
          return try await self.inner.scheduleTransferRuns(request: r, options: o)
        })
    }

    public func startManualTransferRuns(
      request: StartManualTransferRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.StartManualTransferRunsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "startManualTransferRuns",
        action: {
          (r: StartManualTransferRunsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.StartManualTransferRunsResponse
          in
          return try await self.inner.startManualTransferRuns(request: r, options: o)
        })
    }

    public func getTransferRun(
      request: GetTransferRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.TransferRun {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTransferRun",
        action: {
          (r: GetTransferRunRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.TransferRun
          in
          return try await self.inner.getTransferRun(request: r, options: o)
        })
    }

    public func deleteTransferRun(
      request: DeleteTransferRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTransferRun",
        action: {
          (r: DeleteTransferRunRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTransferRun(request: r, options: o)
        })
    }

    public func listTransferRuns(
      request: ListTransferRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ListTransferRunsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTransferRuns",
        action: {
          (r: ListTransferRunsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.ListTransferRunsResponse
          in
          return try await self.inner.listTransferRuns(request: r, options: o)
        })
    }

    public func listTransferLogs(
      request: ListTransferLogsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ListTransferLogsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTransferLogs",
        action: {
          (r: ListTransferLogsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.ListTransferLogsResponse
          in
          return try await self.inner.listTransferLogs(request: r, options: o)
        })
    }

    public func checkValidCreds(
      request: CheckValidCredsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.CheckValidCredsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "checkValidCreds",
        action: {
          (r: CheckValidCredsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryDataTransferV1.CheckValidCredsResponse
          in
          return try await self.inner.checkValidCreds(request: r, options: o)
        })
    }

    public func enrollDataSources(
      request: EnrollDataSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "enrollDataSources",
        action: {
          (r: EnrollDataSourcesRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.enrollDataSources(request: r, options: o)
        })
    }

    public func unenrollDataSources(
      request: UnenrollDataSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "unenrollDataSources",
        action: {
          (r: UnenrollDataSourcesRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.unenrollDataSources(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
