// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A parameter used to define custom fields in a data source definition.
public struct DataSourceParameter: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Parameter identifier.
  public var paramId: Swift.String = Swift.String()

  /// Parameter display name in the user interface.
  public var displayName: Swift.String = Swift.String()

  /// Parameter description.
  public var description: Swift.String = Swift.String()

  /// Parameter type.
  public var type: DataSourceParameter.Type_ = DataSourceParameter.Type_()

  /// Is parameter required.
  public var `required`: Swift.Bool = Swift.Bool()

  /// Deprecated. This field has no effect.
  public var repeated: Swift.Bool = Swift.Bool()

  /// Regular expression which can be used for parameter validation.
  public var validationRegex: Swift.String = Swift.String()

  /// All possible values for the parameter.
  public var allowedValues: [Swift.String] = []

  /// For integer and double values specifies minimum allowed value.
  public var minValue: GoogleWKT.DoubleValue? = nil

  /// For integer and double values specifies maximum allowed value.
  public var maxValue: GoogleWKT.DoubleValue? = nil

  /// Deprecated. This field has no effect.
  public var fields: [DataSourceParameter] = []

  /// Description of the requirements for this field, in case the user input does
  /// not fulfill the regex pattern or min/max values.
  public var validationDescription: Swift.String = Swift.String()

  /// URL to a help document to further explain the naming requirements.
  public var validationHelpUrl: Swift.String = Swift.String()

  /// Cannot be changed after initial creation.
  public var immutable: Swift.Bool = Swift.Bool()

  /// Deprecated. This field has no effect.
  public var recurse: Swift.Bool = Swift.Bool()

  /// If true, it should not be used in new transfers, and it should not be
  /// visible to users.
  public var deprecated: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataSourceParameter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataSourceParameter().with { $0.paramId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let paramId = CodingKeys(stringValue: "paramId")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let type = CodingKeys(stringValue: "type")
    static let `required` = CodingKeys(stringValue: "required")
    static let repeated = CodingKeys(stringValue: "repeated")
    static let validationRegex = CodingKeys(stringValue: "validationRegex")
    static let allowedValues = CodingKeys(stringValue: "allowedValues")
    static let minValue = CodingKeys(stringValue: "minValue")
    static let maxValue = CodingKeys(stringValue: "maxValue")
    static let fields = CodingKeys(stringValue: "fields")
    static let validationDescription = CodingKeys(stringValue: "validationDescription")
    static let validationHelpUrl = CodingKeys(stringValue: "validationHelpUrl")
    static let immutable = CodingKeys(stringValue: "immutable")
    static let recurse = CodingKeys(stringValue: "recurse")
    static let deprecated = CodingKeys(stringValue: "deprecated")

    static let _knownKeys: Set<Swift.String> = [
      "paramId",
      "displayName",
      "description",
      "type",
      "required",
      "repeated",
      "validationRegex",
      "allowedValues",
      "minValue",
      "maxValue",
      "fields",
      "validationDescription",
      "validationHelpUrl",
      "immutable",
      "recurse",
      "deprecated",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .paramId) {
      self.paramId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(DataSourceParameter.Type_.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .`required`) {
      self.`required` = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .repeated) {
      self.repeated = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .validationRegex) {
      self.validationRegex = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .allowedValues) {
      self.allowedValues = value
    }
    self.minValue = try container.decodeIfPresent(GoogleWKT.DoubleValue.self, forKey: .minValue)
    self.maxValue = try container.decodeIfPresent(GoogleWKT.DoubleValue.self, forKey: .maxValue)
    if let value = try container.decodeIfPresent([DataSourceParameter].self, forKey: .fields) {
      self.fields = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .validationDescription)
    {
      self.validationDescription = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .validationHelpUrl) {
      self.validationHelpUrl = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .immutable) {
      self.immutable = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .recurse) {
      self.recurse = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .deprecated) {
      self.deprecated = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.paramId, forKey: .paramId)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.`required`, forKey: .`required`)
    try container.encode(self.repeated, forKey: .repeated)
    try container.encode(self.validationRegex, forKey: .validationRegex)
    try container.encode(self.allowedValues, forKey: .allowedValues)
    try container.encodeIfPresent(self.minValue, forKey: .minValue)
    try container.encodeIfPresent(self.maxValue, forKey: .maxValue)
    try container.encode(self.fields, forKey: .fields)
    try container.encode(self.validationDescription, forKey: .validationDescription)
    try container.encode(self.validationHelpUrl, forKey: .validationHelpUrl)
    try container.encode(self.immutable, forKey: .immutable)
    try container.encode(self.recurse, forKey: .recurse)
    try container.encode(self.deprecated, forKey: .deprecated)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Parameter type.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Type_: Codable, Equatable, Sendable {
    /// Type unspecified.
    case unspecified
    /// String parameter.
    case string
    /// Integer parameter (64-bits).
    /// Will be serialized to json as string.
    case integer
    /// Double precision floating point parameter.
    case double
    /// Boolean parameter.
    case boolean
    /// Deprecated. This field has no effect.
    case record
    /// Page ID for a Google+ Page.
    case plusPage
    /// List of strings parameter.
    case list
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .string: return 1
      case .integer: return 2
      case .double: return 3
      case .boolean: return 4
      case .record: return 5
      case .plusPage: return 6
      case .list: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .string: return "STRING"
      case .integer: return "INTEGER"
      case .double: return "DOUBLE"
      case .boolean: return "BOOLEAN"
      case .record: return "RECORD"
      case .plusPage: return "PLUS_PAGE"
      case .list: return "LIST"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "STRING": self = .string
      case "INTEGER": self = .integer
      case "DOUBLE": self = .double
      case "BOOLEAN": self = .boolean
      case "RECORD": self = .record
      case "PLUS_PAGE": self = .plusPage
      case "LIST": self = .list
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .string
      case 2: self = .integer
      case 3: self = .double
      case 4: self = .boolean
      case 5: self = .record
      case 6: self = .plusPage
      case 7: self = .list
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
      case .string: return try container.encode("STRING")
      case .integer: return try container.encode("INTEGER")
      case .double: return try container.encode("DOUBLE")
      case .boolean: return try container.encode("BOOLEAN")
      case .record: return try container.encode("RECORD")
      case .plusPage: return try container.encode("PLUS_PAGE")
      case .list: return try container.encode("LIST")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.datatransfer.v1.DataSourceParameter"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
