// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol DataTransferServiceStub: Sendable {
    func getDataSource(
      request: GetDataSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.DataSource

    func listDataSources(
      request: ListDataSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ListDataSourcesResponse

    func createTransferConfig(
      request: CreateTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig

    func updateTransferConfig(
      request: UpdateTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig

    func deleteTransferConfig(
      request: DeleteTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func getTransferConfig(
      request: GetTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.TransferConfig

    func listTransferConfigs(
      request: ListTransferConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ListTransferConfigsResponse

    func scheduleTransferRuns(
      request: ScheduleTransferRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ScheduleTransferRunsResponse

    func startManualTransferRuns(
      request: StartManualTransferRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.StartManualTransferRunsResponse

    func getTransferRun(
      request: GetTransferRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.TransferRun

    func deleteTransferRun(
      request: DeleteTransferRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listTransferRuns(
      request: ListTransferRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ListTransferRunsResponse

    func listTransferLogs(
      request: ListTransferLogsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.ListTransferLogsResponse

    func checkValidCreds(
      request: CheckValidCredsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryDataTransferV1.CheckValidCredsResponse

    func enrollDataSources(
      request: EnrollDataSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func unenrollDataSources(
      request: UnenrollDataSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}
