// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A parameter used to define custom fields in a data source definition.
public struct DataSourceParameter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Parameter identifier.
  public var paramId: Swift.String = Swift.String()

  /// Parameter display name in the user interface.
  public var displayName: Swift.String = Swift.String()

  /// Parameter description.
  public var description: Swift.String = Swift.String()

  /// Parameter type.
  public var type: DataSourceParameter.Type_ = DataSourceParameter.Type_()

  /// Is parameter required.
  public var `required`: Swift.Bool = Swift.Bool()

  /// Deprecated. This field has no effect.
  public var repeated: Swift.Bool = Swift.Bool()

  /// Regular expression which can be used for parameter validation.
  public var validationRegex: Swift.String = Swift.String()

  /// All possible values for the parameter.
  public var allowedValues: [Swift.String] = []

  /// For integer and double values specifies minimum allowed value.
  public var minValue: GoogleCloudWkt.DoubleValue? = nil

  /// For integer and double values specifies maximum allowed value.
  public var maxValue: GoogleCloudWkt.DoubleValue? = nil

  /// Deprecated. This field has no effect.
  public var fields: [DataSourceParameter] = []

  /// Description of the requirements for this field, in case the user input does
  /// not fulfill the regex pattern or min/max values.
  public var validationDescription: Swift.String = Swift.String()

  /// URL to a help document to further explain the naming requirements.
  public var validationHelpUrl: Swift.String = Swift.String()

  /// Cannot be changed after initial creation.
  public var immutable: Swift.Bool = Swift.Bool()

  /// Deprecated. This field has no effect.
  public var recurse: Swift.Bool = Swift.Bool()

  /// If true, it should not be used in new transfers, and it should not be
  /// visible to users.
  public var deprecated: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `DataSourceParameter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataSourceParameter().with { $0.paramId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case paramId = "paramId"
    case displayName = "displayName"
    case description = "description"
    case type = "type"
    case `required` = "required"
    case repeated = "repeated"
    case validationRegex = "validationRegex"
    case allowedValues = "allowedValues"
    case minValue = "minValue"
    case maxValue = "maxValue"
    case fields = "fields"
    case validationDescription = "validationDescription"
    case validationHelpUrl = "validationHelpUrl"
    case immutable = "immutable"
    case recurse = "recurse"
    case deprecated = "deprecated"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.paramId = try container.decode(Swift.String.self, forKey: .paramId)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.type = try container.decode(DataSourceParameter.Type_.self, forKey: .type)
    self.`required` = try container.decode(Swift.Bool.self, forKey: .`required`)
    self.repeated = try container.decode(Swift.Bool.self, forKey: .repeated)
    self.validationRegex = try container.decode(Swift.String.self, forKey: .validationRegex)
    self.allowedValues = try container.decode([Swift.String].self, forKey: .allowedValues)
    self.minValue = try container.decodeIfPresent(
      GoogleCloudWkt.DoubleValue.self, forKey: .minValue)
    self.maxValue = try container.decodeIfPresent(
      GoogleCloudWkt.DoubleValue.self, forKey: .maxValue)
    self.fields = try container.decode([DataSourceParameter].self, forKey: .fields)
    self.validationDescription = try container.decode(
      Swift.String.self, forKey: .validationDescription)
    self.validationHelpUrl = try container.decode(Swift.String.self, forKey: .validationHelpUrl)
    self.immutable = try container.decode(Swift.Bool.self, forKey: .immutable)
    self.recurse = try container.decode(Swift.Bool.self, forKey: .recurse)
    self.deprecated = try container.decode(Swift.Bool.self, forKey: .deprecated)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.paramId, forKey: .paramId)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.`required`, forKey: .`required`)
    try container.encode(self.repeated, forKey: .repeated)
    try container.encode(self.validationRegex, forKey: .validationRegex)
    try container.encode(self.allowedValues, forKey: .allowedValues)
    try container.encode(self.minValue, forKey: .minValue)
    try container.encode(self.maxValue, forKey: .maxValue)
    try container.encode(self.fields, forKey: .fields)
    try container.encode(self.validationDescription, forKey: .validationDescription)
    try container.encode(self.validationHelpUrl, forKey: .validationHelpUrl)
    try container.encode(self.immutable, forKey: .immutable)
    try container.encode(self.recurse, forKey: .recurse)
    try container.encode(self.deprecated, forKey: .deprecated)
  }

  /// Parameter type.
  public enum Type_: Codable, Equatable, Sendable {
    /// Type unspecified.
    case unspecified
    /// String parameter.
    case string
    /// Integer parameter (64-bits).
    /// Will be serialized to json as string.
    case integer
    /// Double precision floating point parameter.
    case double
    /// Boolean parameter.
    case boolean
    /// Deprecated. This field has no effect.
    case record
    /// Page ID for a Google+ Page.
    case plusPage
    /// List of strings parameter.
    case list
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .string: return 1
      case .integer: return 2
      case .double: return 3
      case .boolean: return 4
      case .record: return 5
      case .plusPage: return 6
      case .list: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .string: return "STRING"
      case .integer: return "INTEGER"
      case .double: return "DOUBLE"
      case .boolean: return "BOOLEAN"
      case .record: return "RECORD"
      case .plusPage: return "PLUS_PAGE"
      case .list: return "LIST"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "STRING": self = .string
      case "INTEGER": self = .integer
      case "DOUBLE": self = .double
      case "BOOLEAN": self = .boolean
      case "RECORD": self = .record
      case "PLUS_PAGE": self = .plusPage
      case "LIST": self = .list
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .string
      case 2: self = .integer
      case 3: self = .double
      case 4: self = .boolean
      case 5: self = .record
      case 6: self = .plusPage
      case 7: self = .list
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .string: return try container.encode(1)
      case .integer: return try container.encode(2)
      case .double: return try container.encode(3)
      case .boolean: return try container.encode(4)
      case .record: return try container.encode(5)
      case .plusPage: return try container.encode(6)
      case .list: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.datatransfer.v1.DataSourceParameter"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
