// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Options customizing the data transfer schedule.
public struct ScheduleOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// If true, automatic scheduling of data transfer runs for this configuration
  /// will be disabled. The runs can be started on ad-hoc basis using
  /// StartManualTransferRuns API. When automatic scheduling is disabled, the
  /// TransferConfig.schedule field will be ignored.
  public var disableAutoScheduling: Swift.Bool = Swift.Bool()

  /// Specifies time to start scheduling transfer runs. The first run will be
  /// scheduled at or after the start time according to a recurrence pattern
  /// defined in the schedule string. The start time can be changed at any
  /// moment. The time when a data transfer can be triggered manually is not
  /// limited by this option.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Defines time to stop scheduling transfer runs. A transfer run cannot be
  /// scheduled at or after the end time. The end time can be changed at any
  /// moment. The time when a data transfer can be triggered manually is not
  /// limited by this option.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `ScheduleOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ScheduleOptions().with { $0.disableAutoScheduling = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.datatransfer.v1.ScheduleOptions"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
