// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// V2 options customizing different types of data transfer schedule.
/// This field supports existing time-based and manual transfer schedule. Also
/// supports Event-Driven transfer schedule. ScheduleOptionsV2 cannot be used
/// together with ScheduleOptions/Schedule.
public struct ScheduleOptionsV2: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Data transfer schedules.
  public var schedule: OneOf_Schedule? = nil

  /// Initialize a new instance of `ScheduleOptionsV2`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ScheduleOptionsV2().with { $0.timeBasedSchedule = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case timeBasedSchedule = "timeBasedSchedule"
    case manualSchedule = "manualSchedule"
    case eventDrivenSchedule = "eventDrivenSchedule"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var schedule: OneOf_Schedule? = nil
    let scheduleCheckAndSet = {
      if schedule != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'schedule'"))
      }
      schedule = $0
    }
    if let timeBasedSchedule = try container.decodeIfPresent(
      TimeBasedSchedule?.self, forKey: .timeBasedSchedule)
    {
      try scheduleCheckAndSet(.timeBasedSchedule(timeBasedSchedule))
    }
    if let manualSchedule = try container.decodeIfPresent(
      ManualSchedule?.self, forKey: .manualSchedule)
    {
      try scheduleCheckAndSet(.manualSchedule(manualSchedule))
    }
    if let eventDrivenSchedule = try container.decodeIfPresent(
      EventDrivenSchedule?.self, forKey: .eventDrivenSchedule)
    {
      try scheduleCheckAndSet(.eventDrivenSchedule(eventDrivenSchedule))
    }
    self.schedule = schedule
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.schedule {
      switch choice {
      case .timeBasedSchedule(let value):
        try container.encode(value, forKey: .timeBasedSchedule)
      case .manualSchedule(let value):
        try container.encode(value, forKey: .manualSchedule)
      case .eventDrivenSchedule(let value):
        try container.encode(value, forKey: .eventDrivenSchedule)
      }
    }
  }

  /// Data transfer schedules.
  public enum OneOf_Schedule: Codable, Equatable, Sendable {
    /// Time based transfer schedule options. This is the default schedule
    /// option.
    indirect case timeBasedSchedule(TimeBasedSchedule?)
    /// Manual transfer schedule. If set, the transfer run will not be
    /// auto-scheduled by the system, unless the client invokes
    /// StartManualTransferRuns.  This is equivalent to
    /// disable_auto_scheduling = true.
    indirect case manualSchedule(ManualSchedule?)
    /// Event driven transfer schedule options. If set, the transfer will be
    /// scheduled upon events arrial.
    indirect case eventDrivenSchedule(EventDrivenSchedule?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.datatransfer.v1.ScheduleOptionsV2"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
