// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A request to start manual transfer runs.
public struct StartManualTransferRunsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Transfer configuration name in the form:
  /// `projects/{project_id}/transferConfigs/{config_id}` or
  /// `projects/{project_id}/locations/{location_id}/transferConfigs/{config_id}`.
  public var parent: Swift.String = Swift.String()

  /// The requested time specification - this can be a time range or a specific
  /// run_time.
  public var time: TimeOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StartManualTransferRunsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StartManualTransferRunsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let requestedTimeRange = CodingKeys(stringValue: "requestedTimeRange")
    static let requestedRunTime = CodingKeys(stringValue: "requestedRunTime")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "requestedTimeRange",
      "requestedRunTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }

    var time: TimeOneOf? = nil
    let timeCheckAndSet = {
      if time != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'time'"
          ))
      }
      time = $0
    }
    if let requestedTimeRange = try container.decodeIfPresent(
      StartManualTransferRunsRequest.TimeRange?.self, forKey: .requestedTimeRange)
    {
      try timeCheckAndSet(.requestedTimeRange(requestedTimeRange))
    }
    if let requestedRunTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp?.self, forKey: .requestedRunTime)
    {
      try timeCheckAndSet(.requestedRunTime(requestedRunTime))
    }
    self.time = time
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)

    if let choice = self.time {
      switch choice {
      case .requestedTimeRange(let value):
        try container.encode(value, forKey: .requestedTimeRange)
      case .requestedRunTime(let value):
        try container.encode(value, forKey: .requestedRunTime)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A specification for a time range, this will request transfer runs with
  /// run_time between start_time (inclusive) and end_time (exclusive).
  public struct TimeRange: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Start time of the range of transfer runs. For example,
    /// `"2017-05-25T00:00:00+00:00"`. The start_time must be strictly less than
    /// the end_time. Creates transfer runs where run_time is in the range
    /// between start_time (inclusive) and end_time (exclusive).
    public var startTime: GoogleWKT.WKTTimestamp? = nil

    /// End time of the range of transfer runs. For example,
    /// `"2017-05-30T00:00:00+00:00"`. The end_time must not be in the future.
    /// Creates transfer runs where run_time is in the range between start_time
    /// (inclusive) and end_time (exclusive).
    public var endTime: GoogleWKT.WKTTimestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TimeRange`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TimeRange().with { $0.startTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let startTime = CodingKeys(stringValue: "startTime")
      static let endTime = CodingKeys(stringValue: "endTime")

      static let _knownKeys: Set<Swift.String> = [
        "startTime",
        "endTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.startTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .startTime)
      self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.startTime, forKey: .startTime)
      try container.encodeIfPresent(self.endTime, forKey: .endTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.bigquery.datatransfer.v1.StartManualTransferRunsRequest.TimeRange"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The requested time specification - this can be a time range or a specific
  /// run_time.
  public enum TimeOneOf: Codable, Equatable, Sendable {
    /// A time_range start and end timestamp for historical data files or reports
    /// that are scheduled to be transferred by the scheduled transfer run.
    /// requested_time_range must be a past time and cannot include future time
    /// values.
    indirect case requestedTimeRange(StartManualTransferRunsRequest.TimeRange?)
    /// A run_time timestamp for historical data files or reports
    /// that are scheduled to be transferred by the scheduled transfer run.
    /// requested_run_time must be a past time and cannot include future time
    /// values.
    indirect case requestedRunTime(GoogleWKT.WKTTimestamp?)
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.bigquery.datatransfer.v1.StartManualTransferRunsRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
