// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents a data transfer configuration. A transfer configuration
/// contains all metadata needed to perform a data transfer. For example,
/// `destination_dataset_id` specifies where data should be stored.
/// When a new transfer configuration is created, the specified
/// `destination_dataset_id` is created when needed and shared with the
/// appropriate data source service account.
public struct TransferConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the transfer config.
  /// Transfer config names have the form either
  /// `projects/{project_id}/locations/{region}/transferConfigs/{config_id}` or
  /// `projects/{project_id}/transferConfigs/{config_id}`,
  /// where `config_id` is usually a UUID, even though it is not
  /// guaranteed or required. The name is ignored when creating a transfer
  /// config.
  public var name: Swift.String = Swift.String()

  /// User specified display name for the data transfer.
  public var displayName: Swift.String = Swift.String()

  /// Data source ID. This cannot be changed once data transfer is created. The
  /// full list of available data source IDs can be returned through an API call:
  /// https://cloud.google.com/bigquery-transfer/docs/reference/datatransfer/rest/v1/projects.locations.dataSources/list
  public var dataSourceId: Swift.String = Swift.String()

  /// Parameters specific to each data source. For more information see the
  /// bq tab in the 'Setting up a data transfer' section for each data source.
  /// For example the parameters for Cloud Storage transfers are listed here:
  /// https://cloud.google.com/bigquery-transfer/docs/cloud-storage-transfer#bq
  public var params: GoogleWKT.WKTStruct? = nil

  /// Data transfer schedule.
  /// If the data source does not support a custom schedule, this should be
  /// empty. If it is empty, the default value for the data source will be used.
  /// The specified times are in UTC.
  /// Examples of valid format:
  /// `1st,3rd monday of month 15:30`,
  /// `every wed,fri of jan,jun 13:15`, and
  /// `first sunday of quarter 00:00`.
  /// See more explanation about the format here:
  /// https://cloud.google.com/appengine/docs/flexible/python/scheduling-jobs-with-cron-yaml#the_schedule_format
  ///
  /// NOTE: The minimum interval time between recurring transfers depends on the
  /// data source; refer to the documentation for your data source.
  public var schedule: Swift.String = Swift.String()

  /// Options customizing the data transfer schedule.
  public var scheduleOptions: ScheduleOptions? = nil

  /// Options customizing different types of data transfer schedule.
  /// This field replaces "schedule" and "schedule_options" fields.
  /// ScheduleOptionsV2 cannot be used together with ScheduleOptions/Schedule.
  public var scheduleOptionsV2: ScheduleOptionsV2? = nil

  /// The number of days to look back to automatically refresh the data.
  /// For example, if `data_refresh_window_days = 10`, then every day
  /// BigQuery reingests data for [today-10, today-1], rather than ingesting data
  /// for just [today-1].
  /// Only valid if the data source supports the feature. Set the value to 0
  /// to use the default value.
  public var dataRefreshWindowDays: Swift.Int32 = Swift.Int32()

  /// Is this config disabled. When set to true, no runs will be scheduled for
  /// this transfer config.
  public var disabled: Swift.Bool = Swift.Bool()

  /// Output only. Data transfer modification time. Ignored by server on input.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Next time when data transfer will run.
  public var nextRunTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. State of the most recently updated transfer run.
  public var state: TransferState = TransferState()

  /// Deprecated. Unique ID of the user on whose behalf transfer is done.
  public var userId: Swift.Int64 = Swift.Int64()

  /// Output only. Region in which BigQuery dataset is located.
  public var datasetRegion: Swift.String = Swift.String()

  /// Pub/Sub topic where notifications will be sent after transfer runs
  /// associated with this transfer config finish.
  ///
  /// The format for specifying a pubsub topic is:
  /// `projects/{project_id}/topics/{topic_id}`
  public var notificationPubsubTopic: Swift.String = Swift.String()

  /// Email notifications will be sent according to these preferences
  /// to the email address of the user who owns this transfer config.
  public var emailPreferences: EmailPreferences? = nil

  /// Output only. Information about the user whose credentials are used to
  /// transfer data. Populated only for `transferConfigs.get` requests. In case
  /// the user information is not available, this field will not be populated.
  public var ownerInfo: UserInfo? = nil

  /// The encryption configuration part. Currently, it is only used for the
  /// optional KMS key name. The BigQuery service account of your project must be
  /// granted permissions to use the key. Read methods will return the key name
  /// applied in effect. Write methods will apply the key if it is present, or
  /// otherwise try to apply project default keys if it is absent.
  public var encryptionConfiguration: EncryptionConfiguration? = nil

  /// Output only. Error code with detailed information about reason of the
  /// latest config failure.
  public var error: GoogleRpc.Status? = nil

  /// The desination of the transfer config.
  public var destination: DestinationOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TransferConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let destinationDatasetId = CodingKeys(stringValue: "destinationDatasetId")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let dataSourceId = CodingKeys(stringValue: "dataSourceId")
    static let params = CodingKeys(stringValue: "params")
    static let schedule = CodingKeys(stringValue: "schedule")
    static let scheduleOptions = CodingKeys(stringValue: "scheduleOptions")
    static let scheduleOptionsV2 = CodingKeys(stringValue: "scheduleOptionsV2")
    static let dataRefreshWindowDays = CodingKeys(stringValue: "dataRefreshWindowDays")
    static let disabled = CodingKeys(stringValue: "disabled")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let nextRunTime = CodingKeys(stringValue: "nextRunTime")
    static let state = CodingKeys(stringValue: "state")
    static let userId = CodingKeys(stringValue: "userId")
    static let datasetRegion = CodingKeys(stringValue: "datasetRegion")
    static let notificationPubsubTopic = CodingKeys(stringValue: "notificationPubsubTopic")
    static let emailPreferences = CodingKeys(stringValue: "emailPreferences")
    static let ownerInfo = CodingKeys(stringValue: "ownerInfo")
    static let encryptionConfiguration = CodingKeys(stringValue: "encryptionConfiguration")
    static let error = CodingKeys(stringValue: "error")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "destinationDatasetId",
      "displayName",
      "dataSourceId",
      "params",
      "schedule",
      "scheduleOptions",
      "scheduleOptionsV2",
      "dataRefreshWindowDays",
      "disabled",
      "updateTime",
      "nextRunTime",
      "state",
      "userId",
      "datasetRegion",
      "notificationPubsubTopic",
      "emailPreferences",
      "ownerInfo",
      "encryptionConfiguration",
      "error",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dataSourceId) {
      self.dataSourceId = value
    }
    self.params = try container.decodeIfPresent(GoogleWKT.WKTStruct.self, forKey: .params)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .schedule) {
      self.schedule = value
    }
    self.scheduleOptions = try container.decodeIfPresent(
      ScheduleOptions.self, forKey: .scheduleOptions)
    self.scheduleOptionsV2 = try container.decodeIfPresent(
      ScheduleOptionsV2.self, forKey: .scheduleOptionsV2)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .dataRefreshWindowDays) {
      self.dataRefreshWindowDays = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disabled) {
      self.disabled = value
    }
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.nextRunTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .nextRunTime)
    if let value = try container.decodeIfPresent(TransferState.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .userId) {
      self.userId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .datasetRegion) {
      self.datasetRegion = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .notificationPubsubTopic)
    {
      self.notificationPubsubTopic = value
    }
    self.emailPreferences = try container.decodeIfPresent(
      EmailPreferences.self, forKey: .emailPreferences)
    self.ownerInfo = try container.decodeIfPresent(UserInfo.self, forKey: .ownerInfo)
    self.encryptionConfiguration = try container.decodeIfPresent(
      EncryptionConfiguration.self, forKey: .encryptionConfiguration)
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)

    var destination: DestinationOneOf? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let destinationDatasetId = try container.decodeIfPresent(
      Swift.String.self, forKey: .destinationDatasetId)
    {
      try destinationCheckAndSet(.destinationDatasetId(destinationDatasetId))
    }
    self.destination = destination
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.dataSourceId, forKey: .dataSourceId)
    try container.encodeIfPresent(self.params, forKey: .params)
    try container.encode(self.schedule, forKey: .schedule)
    try container.encodeIfPresent(self.scheduleOptions, forKey: .scheduleOptions)
    try container.encodeIfPresent(self.scheduleOptionsV2, forKey: .scheduleOptionsV2)
    try container.encode(self.dataRefreshWindowDays, forKey: .dataRefreshWindowDays)
    try container.encode(self.disabled, forKey: .disabled)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.nextRunTime, forKey: .nextRunTime)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.userId, forKey: .userId)
    try container.encode(self.datasetRegion, forKey: .datasetRegion)
    try container.encode(self.notificationPubsubTopic, forKey: .notificationPubsubTopic)
    try container.encodeIfPresent(self.emailPreferences, forKey: .emailPreferences)
    try container.encodeIfPresent(self.ownerInfo, forKey: .ownerInfo)
    try container.encodeIfPresent(self.encryptionConfiguration, forKey: .encryptionConfiguration)
    try container.encodeIfPresent(self.error, forKey: .error)

    if let choice = self.destination {
      switch choice {
      case .destinationDatasetId(let value):
        try container.encode(value, forKey: .destinationDatasetId)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The desination of the transfer config.
  public enum DestinationOneOf: Codable, Equatable, Sendable {
    /// The BigQuery target dataset id.
    case destinationDatasetId(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.datatransfer.v1.TransferConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
