// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleRpc

/// Represents a data transfer run.
public struct TransferRun: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the transfer run.
  /// Transfer run names have the form
  /// `projects/{project_id}/locations/{location}/transferConfigs/{config_id}/runs/{run_id}`.
  /// The name is ignored when creating a transfer run.
  public var name: Swift.String = Swift.String()

  /// Minimum time after which a transfer run can be started.
  public var scheduleTime: GoogleCloudWkt.Timestamp? = nil

  /// For batch transfer runs, specifies the date and time of the data should be
  /// ingested.
  public var runTime: GoogleCloudWkt.Timestamp? = nil

  /// Status of the transfer run.
  public var errorStatus: GoogleRpc.Status? = nil

  /// Output only. Time when transfer run was started.
  /// Parameter ignored by server for input requests.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Time when transfer run ended.
  /// Parameter ignored by server for input requests.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Last time the data transfer run state was updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Parameters specific to each data source. For more information
  /// see the bq tab in the 'Setting up a data transfer' section for each data
  /// source. For example the parameters for Cloud Storage transfers are listed
  /// here:
  /// https://cloud.google.com/bigquery-transfer/docs/cloud-storage-transfer#bq
  public var params: GoogleCloudWkt.Struct? = nil

  /// Output only. Data source id.
  public var dataSourceId: Swift.String = Swift.String()

  /// Data transfer run state. Ignored for input requests.
  public var state: TransferState = TransferState()

  /// Deprecated. Unique ID of the user on whose behalf transfer is done.
  public var userId: Swift.Int64 = Swift.Int64()

  /// Output only. Describes the schedule of this transfer run if it was
  /// created as part of a regular schedule. For batch transfer runs that are
  /// scheduled manually, this is empty.
  /// NOTE: the system might choose to delay the schedule depending on the
  /// current load, so `schedule_time` doesn't always match this.
  public var schedule: Swift.String = Swift.String()

  /// Output only. Pub/Sub topic where a notification will be sent after this
  /// transfer run finishes.
  ///
  /// The format for specifying a pubsub topic is:
  /// `projects/{project_id}/topics/{topic_id}`
  public var notificationPubsubTopic: Swift.String = Swift.String()

  /// Output only. Email notifications will be sent according to these
  /// preferences to the email address of the user who owns the transfer config
  /// this run was derived from.
  public var emailPreferences: EmailPreferences? = nil

  /// Data transfer destination.
  public var destination: OneOf_Destination? = nil

  /// Initialize a new instance of `TransferRun`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferRun().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case scheduleTime = "scheduleTime"
    case runTime = "runTime"
    case errorStatus = "errorStatus"
    case startTime = "startTime"
    case endTime = "endTime"
    case updateTime = "updateTime"
    case params = "params"
    case destinationDatasetId = "destinationDatasetId"
    case dataSourceId = "dataSourceId"
    case state = "state"
    case userId = "userId"
    case schedule = "schedule"
    case notificationPubsubTopic = "notificationPubsubTopic"
    case emailPreferences = "emailPreferences"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.scheduleTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .scheduleTime)
    self.runTime = try container.decodeIfPresent(GoogleCloudWkt.Timestamp.self, forKey: .runTime)
    self.errorStatus = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .errorStatus)
    self.startTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleCloudWkt.Timestamp.self, forKey: .endTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.params = try container.decodeIfPresent(GoogleCloudWkt.Struct.self, forKey: .params)
    self.dataSourceId = try container.decode(Swift.String.self, forKey: .dataSourceId)
    self.state = try container.decode(TransferState.self, forKey: .state)
    self.userId = try container.decode(Swift.Int64.self, forKey: .userId)
    self.schedule = try container.decode(Swift.String.self, forKey: .schedule)
    self.notificationPubsubTopic = try container.decode(
      Swift.String.self, forKey: .notificationPubsubTopic)
    self.emailPreferences = try container.decodeIfPresent(
      EmailPreferences.self, forKey: .emailPreferences)

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let destinationDatasetId = try container.decodeIfPresent(
      Swift.String.self, forKey: .destinationDatasetId)
    {
      try destinationCheckAndSet(.destinationDatasetId(destinationDatasetId))
    }
    self.destination = destination
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.scheduleTime, forKey: .scheduleTime)
    try container.encode(self.runTime, forKey: .runTime)
    try container.encode(self.errorStatus, forKey: .errorStatus)
    try container.encode(self.startTime, forKey: .startTime)
    try container.encode(self.endTime, forKey: .endTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.params, forKey: .params)
    try container.encode(self.dataSourceId, forKey: .dataSourceId)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.userId, forKey: .userId)
    try container.encode(self.schedule, forKey: .schedule)
    try container.encode(self.notificationPubsubTopic, forKey: .notificationPubsubTopic)
    try container.encode(self.emailPreferences, forKey: .emailPreferences)

    if let choice = self.destination {
      switch choice {
      case .destinationDatasetId(let value):
        try container.encode(value, forKey: .destinationDatasetId)
      }
    }
  }

  /// Data transfer destination.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// Output only. The BigQuery target dataset id.
    case destinationDatasetId(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.datatransfer.v1.TransferRun"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
